import { z } from "zod";

export const krakend = z.object({
  version: z.enum(["3"]),
  host: z.string().array(),
  debug_endpoint: z.boolean().default(false),
  sequential_start: z.boolean().default(false),
  async_agent: z.object({}),
  name: z.string().default("KrakenD configuration at MyCompany"),
  port: z.number().min(0).max(65535).default(8080),
  timeout: z.string().default("2s"),
  output_encoding: z
    .enum([
      "json",
      "fast-json",
      "json-collection",
      "xml",
      "negotiate",
      "string",
      "no-op",
    ])
    .default("json"),
  read_timeout: z.string().default("0s"),
  read_header_timeout: z.string().default("0s"),
  write_timeout: z.string().default("0s"),
  idle_timeout: z.string().default("0s"),
  dialer_timeout: z.string().default("0s"),
  dialer_keep_alive: z.string().default("15s"),
  dialer_fallback_delay: z.string().default("300ms"),
  disable_compression: z.boolean().default(false),
  disable_keep_alives: z.boolean().default(false),
  max_idle_connections: z.number().default(0),
  max_idle_connections_per_host: z.number().default(250),
  idle_connection_timeout: z.string().default("0s"),
  response_header_timeout: z.string().default("0s"),
  expect_continue_timeout: z.string().default("0s"),
  disable_rest: z.boolean().default(false),
  allow_insecure_connections: z.boolean().default(false),
  tls: z.object({}),
  plugin: z.object({
    pattern: z.string().default(".so"),
    folder: z.string().default("/opt/krakend/plugins/"),
  }),
  endpoints: z.object({}).array(),
  extra_config: z.object({}),
});
